# Generated by Django 4.1.4 on 2023-01-07 16:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DeliveryMethod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Название')),
                ('description', models.TextField(max_length=1000, verbose_name='Описание')),
            ],
            options={
                'verbose_name': 'способ доставки',
                'verbose_name_plural': 'способы доставки',
                'db_table': 'delivery_methods',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('payment_at', models.DateTimeField(blank=True, null=True, verbose_name='Дата оплаты')),
            ],
            options={
                'verbose_name': 'заказ',
                'verbose_name_plural': 'заказы',
                'db_table': 'orders',
                'ordering': ['-payment_status', '-payment_at'],
            },
        ),
        migrations.CreateModel(
            name='PaymentMethod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Название')),
            ],
            options={
                'verbose_name': 'способ оплаты',
                'verbose_name_plural': 'способы оплаты',
                'db_table': 'payment_methods',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='PaymentStatuses',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Название')),
                ('priority', models.IntegerField(default=0, verbose_name='Приоритет')),
            ],
            options={
                'verbose_name': 'статус оплаты',
                'verbose_name_plural': 'статусы оплаты',
                'db_table': 'payment_statuses',
                'ordering': ['-priority'],
            },
        ),
        migrations.CreateModel(
            name='OrderItems',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_amount', models.IntegerField(default=1, verbose_name='Количество товара')),
                ('product_price', models.FloatField(default=0, verbose_name='Цена товара')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order', to='app_orders.order', verbose_name='Заказ')),
            ],
            options={
                'verbose_name': 'товар заказа',
                'verbose_name_plural': 'товары заказа',
                'db_table': 'order_items',
                'ordering': ['id'],
            },
        ),
    ]
