# Generated by Django 4.1.4 on 2023-01-07 16:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('app_product', '0001_initial'),
        ('app_orders', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitems',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_product', to='app_product.product', verbose_name='Товар'),
        ),
        migrations.AddField(
            model_name='order',
            name='method_delivery',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='method_delivery', to='app_orders.deliverymethod', verbose_name='Способ доставки'),
        ),
        migrations.AddField(
            model_name='order',
            name='method_payment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='method_payment', to='app_orders.paymentmethod', verbose_name='Способ оплаты'),
        ),
        migrations.AddField(
            model_name='order',
            name='payment_status',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payment_status', to='app_orders.paymentstatuses', verbose_name='Статус оплаты'),
        ),
    ]
