# Generated by Django 4.1.4 on 2023-01-07 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SiteSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_delivery_limit', models.IntegerField(default=2000, verbose_name='Лимит суммы для бесплатной доставки')),
                ('order_delivery_price', models.IntegerField(default=200, verbose_name='Стоимость доставки')),
                ('order_delivery_express', models.IntegerField(default=500, verbose_name='Стоимость экспресс-доставки')),
                ('access_to_auth_when_auth', models.BooleanField(default=True, verbose_name='Доступ к аутентификации, когда авторизован')),
                ('avatar_image_max_size_mb', models.FloatField(default=2, verbose_name='Максимальный размер аватарки, МБ')),
            ],
            options={
                'verbose_name': 'настройка сайта',
                'verbose_name_plural': 'настройки сайта',
                'db_table': 'settings',
            },
        ),
    ]
