# Generated by Django 4.1.4 on 2023-01-07 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_settings', '0002_sitesettings_popular_product_amount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sitesettings',
            name='popular_product_amount',
            field=models.IntegerField(default=8, verbose_name='Количество популярных товаров на главной'),
        ),
    ]
