# Generated by Django 4.1.4 on 2023-01-08 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_settings', '0003_alter_sitesettings_popular_product_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='product_page_amount',
            field=models.IntegerField(default=2, verbose_name='Количество товаров на странице'),
        ),
    ]
