# Generated by Django 4.1.4 on 2023-01-07 16:39

from django.db import migrations, models
import django.db.models.deletion
import mptt.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Attribute',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='AttributeName',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=255, verbose_name='Название атрибута')),
            ],
            options={
                'verbose_name': 'атрибут',
                'verbose_name_plural': 'атрибуты',
                'db_table': 'attributes',
            },
        ),
        migrations.CreateModel(
            name='AttributeValue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(db_index=True, max_length=255, verbose_name='Значение атрибута товара')),
            ],
            options={
                'verbose_name': 'значение атрибута',
                'verbose_name_plural': 'значения атрибутов',
                'db_table': 'attribute_values',
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(db_index=True, max_length=100, verbose_name='Название')),
                ('icon_link', models.CharField(blank=True, max_length=1000, null=True, verbose_name='Ссылка на иконку')),
                ('active', models.BooleanField(default=True, verbose_name='Категория активна')),
                ('favourite', models.BooleanField(default=False, verbose_name='Избранное')),
                ('lft', models.PositiveIntegerField(editable=False)),
                ('rght', models.PositiveIntegerField(editable=False)),
                ('tree_id', models.PositiveIntegerField(db_index=True, editable=False)),
                ('level', models.PositiveIntegerField(editable=False)),
            ],
            options={
                'verbose_name': 'категория',
                'verbose_name_plural': 'категории',
                'db_table': 'categories',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=1000, verbose_name='Название')),
                ('description', models.TextField(blank=True, max_length=2000, verbose_name='Описание')),
                ('description_detailed', models.TextField(blank=True, max_length=5000, verbose_name='Подробное описание')),
                ('price', models.FloatField(default=0, verbose_name='Цена')),
                ('remains', models.IntegerField(default=0, verbose_name='Остаток')),
                ('active', models.BooleanField(default=True, verbose_name='Активный товар')),
                ('sorting_index', models.IntegerField(default=0, verbose_name='Индекс сортировки')),
                ('limited_edition', models.BooleanField(default=False, verbose_name='Ограниченный тираж')),
                ('sold_amount', models.IntegerField(default=0, verbose_name='Количество покупок')),
                ('add_at', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Дата добавления')),
                ('attributes', models.ManyToManyField(through='app_product.Attribute', to='app_product.attributename')),
                ('category', mptt.fields.TreeForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='category', to='app_product.category', verbose_name='Категория')),
            ],
            options={
                'verbose_name': 'товар',
                'verbose_name_plural': 'товары',
                'db_table': 'products',
                'ordering': ['-sold_amount'],
            },
        ),
        migrations.CreateModel(
            name='PropertyName',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=255, verbose_name='Характеристика товара')),
            ],
            options={
                'verbose_name': 'характеристика',
                'verbose_name_plural': 'характеристики',
                'db_table': 'product_properties',
            },
        ),
        migrations.CreateModel(
            name='PropertyValue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(db_index=True, max_length=255, verbose_name='Значение характеристики товара')),
            ],
            options={
                'verbose_name': 'значение',
                'verbose_name_plural': 'значения',
                'db_table': 'property_value',
            },
        ),
        migrations.CreateModel(
            name='Property',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_property', to='app_product.product', verbose_name='Товар')),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='property', to='app_product.propertyname', verbose_name='Характеристика')),
                ('value', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_product.propertyvalue', verbose_name='Значение характеристики')),
            ],
        ),
        migrations.CreateModel(
            name='ProductImages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='images/products/', verbose_name='Изображение товара')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_image', to='app_product.product', verbose_name='Товар')),
            ],
            options={
                'verbose_name': 'изображение',
                'verbose_name_plural': 'изображения',
                'db_table': 'product_images',
                'ordering': ['id'],
            },
        ),
        migrations.AddField(
            model_name='product',
            name='options',
            field=models.ManyToManyField(through='app_product.Property', to='app_product.propertyname'),
        ),
        migrations.CreateModel(
            name='HistoryProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product', to='app_product.product', verbose_name='Товар')),
            ],
        ),
    ]
