# Generated by Django 4.1.4 on 2023-01-07 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_product', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='image_link',
            field=models.CharField(blank=True, max_length=1000, null=True, verbose_name='Ссылка на изображение'),
        ),
    ]
