# Generated by Django 4.1.4 on 2023-01-07 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_product', '0003_category_image_link'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ['sort_index'], 'verbose_name': 'категория', 'verbose_name_plural': 'категории'},
        ),
        migrations.AddField(
            model_name='category',
            name='sort_index',
            field=models.IntegerField(default=0, verbose_name='Индекс сортировки'),
        ),
    ]
