# Generated by Django 4.1.4 on 2023-01-08 07:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_product', '0004_alter_category_options_category_sort_index'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ['sort_index', 'id'], 'verbose_name': 'категория', 'verbose_name_plural': 'категории'},
        ),
    ]
