# Generated by Django 4.1.4 on 2023-01-08 07:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_product', '0006_category_icon_category_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='icon_link',
        ),
        migrations.RemoveField(
            model_name='category',
            name='image_link',
        ),
    ]
